## The data here is of generic interest to modules in different namespaces hence this is marked as global.
## Replace your domain names here.
## mosip-api-host:  External public access. (Typically required only in production rollouts).
## mosip-api-internal-host: Internal secure access over Wireguard.
## By default all domains and subdomains listed below point to mosip-api-internal-host. Modify this default behavior ONLY in production rollout as follows:
##     mosip-prereg-host:  Points to mosip-api-host.
##     mosip-pmp-host: Points to mosip-api-host.

apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: default
data:
  installation-name: ${ENV}
  installation-domain: ${ENV}.credissuer.com
  mosip-version: ${VERSION}
  mosip-api-host: api.${ENV}.credissuer.com
  mosip-api-internal-host: api-internal.${ENV}.credissuer.com
  mosip-prereg-host: prereg.${ENV}.credissuer.com
  mosip-activemq-host: activemq.${ENV}.credissuer.com
  mosip-kibana-host: kibana.${ENV}.credissuer.com
  mosip-admin-host: admin.${ENV}.credissuer.com
  mosip-regclient-host: regclient.${ENV}.credissuer.com
  mosip-minio-host: minio.${ENV}.credissuer.com
  mosip-kafka-host: kafka.${ENV}.credissuer.com
  mosip-iam-external-host: iam.${ENV}.credissuer.com
  mosip-postgres-host: postgres.${ENV}.credissuer.com
  mosip-pmp-host: pmp.${ENV}.credissuer.com
  mosip-resident-host: resident.${ENV}.credissuer.com
  mosip-compliance-host: compliance.${ENV}.credissuer.com
  mosip-esignet-host: esignet.${ENV}.credissuer.com
  mosip-smtp-host: smtp.${ENV}.credissuer.com
  mosip-signup-host: signup.${ENV}.credissuer.com
  is_glowroot_env: absent
